### ISSUE TITLE
`null` response from server is returned as empty object

### ISSUE THREAD

**Issue by manoharank** [ember-cli/ember-ajax#158] opened 2016-09-11 11:19 UTC
Upgrading to 2.5.0 from 0.7.1. #126 breaks my app, I expect a `null` value from the API, but now this returns an empty object, which breaks all my `{{#if data}}`. cc @alexlafroscia @taras

**Comment by taras** [comment] 2016-09-11 11:27
@manoharank we made that change to ensure that payload always has a consistent errors object, but it looks like in the process we forced payload to become a hash. This is a bug.

I believe we should be doing something like this instead:

```diff
  handleResponse(status, headers, payload, requestData) {
-    payload = (payload === null || payload === undefined) ? {} : payload;
    const errors = this.normalizeErrorResponse(status, headers, payload);

    if (this.isSuccess(status, headers, payload)) {
      return payload;
```
and 

```diff
  normalizeErrorResponse(status, headers, payload) {
+ payload = isNone(payload) ? {} : payload;

    if (isArray(payload.errors)) {
```

This should address your problem. If @alexlafroscia agrees, would you be open to submitting a PR for this?

**Comment by manoharank** [comment] 2016-09-11 11:35
@taras `Ember.isNone` returns `true` for `null`. We can have `payload = (payload === undefined) ? {} : payload; `.

**Comment by taras** [comment] 2016-09-11 11:37
@manoharank `Ember.isNone(null) //=> true` will work as intended in the example that I showed above because we're not reassigning payload in `handleResponse`.

**Comment by manoharank** [comment] 2016-09-11 11:41
@taras yes, just now looked the function name. And also I have raised one more bug related to `normalizeErrorResponse` #157 .

**Comment by dwickern** [comment] 2016-10-12 17:11
If ember-ajax converts a `null` response (or an empty response with a 204 status code) into `{}`, ember-data will treat it as a record and expect it to have an `id`.

Ember-ajax should not convert a valid response into something else.

**Comment by XaserAcheron** [comment] 2016-12-12 20:09
Confirmed -- pushed a failing test to my fork.

Interestingly, there was already a unit test responsible for checking if payloads remained unchanged, but the `null` and `undefined` cases were being compared to the empty object, which seems like the big "oops" here. After correcting the test, the issue was reproduced as described.

The fix suggested by @taras indeed makes everything pass again, BTW. :)

**Comment by alexlafroscia** [comment] 2017-03-27 03:08
Closed by #232

**Closed by alexlafroscia** 2017-03-27 03:08 UTC
Labels: needs-test
