### ISSUE TITLE
Having trouble with acceptance tests & error handling

### ISSUE THREAD

**Issue by ebenoist** [ember-cli/ember-ajax#12] opened 2015-10-06 15:36 UTC
I've attempted to create a ember-ajax wrapper with some convenience methods and a general error catch. The error catch looks like this:

```JavaScript
...
  myConvenientGET(method, url, options) {
    let req = this.get('ajax').request(url, options);

    req.catch(error => {
      error.errors.forEach((error) => {
        this.get('flash').add({
          message: error.detail,
          type: 'alert-error'
        });
      });

      throw error;
    });

    return req;
  }
```

The problem I'm having is that in an acceptance test which includes a bad response, the thrown error bubbles all the way to the site of the acceptance test, but I don't see anyway of handling it. I've tried to wrap the test in `try{}catch(e){}` and qunit's `throws`. My question is when handling errors like these I want to throw so that the promise chain is rejected, but how can we handle these expected errors at the acceptance test level?

Is this how a general error catch should be done using ember-ajax?

**Comment by yaymukund** [comment] 2015-12-02 16:38
I second this. It looks like the ember test helpers are based on promises, so I feel like this should be possible:

```js
andThen(() => {
  click('.cause-error');
}).catch(e => { ... });
```

But it doesn't actually catch the error.

**Comment by alexlafroscia** [comment] 2016-01-22 19:17
Hey @ebenoist, I know this issue is pretty old but I'd like to try to get it solved, if we can :smile: 

There's a test case included in the application that seems to cover what you were talking around, regarding testing an error case.  You can find it here: https://github.com/ember-cli/ember-ajax/blob/f9ca0baf4fc038b118bb923c85638b383563c0a3/tests/acceptance/ajax-get-test.js#L39-L55

It seems like the errors shouldn't bubble all the way up any more; if you're able to update to the latest version of `ember-ajax` and verify that the behavior works the way you think it should, I'd love to get this taken care of before our 2.0 release!

**Comment by ebenoist** [comment] 2016-01-22 19:38
@alexlafroscia Awesome! I'll see if I can take a look (not really work in Ember atm). @the83 might be interested in this as well.

**Comment by alexlafroscia** [comment] 2016-01-22 19:49
Thanks! I really appreciate it :)

After looking at it a bit more and thinking about it, I'm not sure that the test case there actually covers the behavior you were talking about after all.  You wanted to test a case where the rejected promise is never caught, right?  That test seems to show a situation where there is an error case, but if you look at the actual promise that is failing, a `.catch` is applied that does _not_ go and throw the error again, meaning that the error would actually be caught at that point.  The code I'm referring to can be found [here](https://github.com/ember-cli/ember-ajax/blob/5b34bf79c057e2a081338a08772396e872de11eb/tests/dummy/app/components/ajax-get.js#L16).

If you agree that the test I linked to before doesn't actually match what you were trying to do, I'll try to make an actual test case for it so we can verify how you actually go about catching those errors.

I'm wondering, though, if the error being thrown the way it is is actually the desired behavior... Since the acceptance tests should be verifying what your application actually does, you probably don't _want_ that error bubbling up all the way (so that it could be caught by `QUnit.assert` or whatever).  Something along the line should be catching and handling the error; if you wanted to try to catch the error in QUnit, that would mean that the Promise's error wasn't being handled by your application.  I'd love to get your take on that to understand the problem better.

**Comment by taras** [comment] 2016-01-22 19:51
@alexlafroscia you're right. A promise that doesn't have a catch should bubble up. This is expected behaviour.

**Comment by taras** [comment] 2016-01-22 19:53
Here is another example where an error is not handled and it's being caught in the test instead https://github.com/ember-cli/ember-ajax/blob/master/tests/integration/components/async-widget-test.js#L112

**Comment by alexlafroscia** [comment] 2016-01-22 21:40
Oh okay, so based on that comment it looks like you can catch the error in the test if you want to, even if you really should be catching the error in the application somewhere.  I had missed that test case when looking through them earlier.  Based on that, I think that this is probably ready to be closed, but I'd like to check that @ebenoist is satisfied with that first.

**Comment by alexlafroscia** [comment] 2016-01-30 17:22
I'm going to close this, feel free to open it again @ebenoist if you are still having this issue.

**Closed by alexlafroscia** 2016-01-30 17:22 UTC

**Comment by erichonkanen** [comment] 2018-01-10 16:30
not sure if related but we are having trouble in our acceptance test where our `throw` is bubbling up and causing the test to fail (it's bubbling up into the test container)
```
        try {
            yield session.authenticate('authenticator:mt', email, password);
        } catch (err) {
            changeset.pushErrors('nonFieldErrors', err.error_description);
            throw Error('failed to authenticate');
```
